version: '3'

services:
  backend:
    image: sistema_signgo
    container_name: signgo
    restart: always
    ports:
      - '8080:8080'

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - '443:443'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - backend
