# Generated by Django 5.0.6 on 2024-12-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='TokenAuth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firmante',
            name='TokenAuth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
