# Generated by Django 5.0.6 on 2024-12-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0002_envio_tokenauth_firmante_tokenauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmante',
            name='Datos',
            field=models.BooleanField(default=False),
        ),
    ]
