# Generated by Django 5.0.6 on 2024-12-20 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0003_firmante_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presigned_url', models.TextField(null=True)),
                ('UsuarioSistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmante_imagen', to='flujofirma.firmante')),
            ],
        ),
        migrations.CreateModel(
            name='DatosFirmante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('with_video', models.BooleanField(default=False)),
                ('imagen_dpi_frontal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagen_frontal', to='flujofirma.imagen')),
                ('imagen_dpi_posterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagen_posterior', to='flujofirma.imagen')),
                ('imagen_persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagen_persona', to='flujofirma.imagen')),
            ],
        ),
    ]
