# Generated by Django 5.0.6 on 2024-12-20 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0004_imagen_datosfirmante'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosfirmante',
            name='Firmante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmante_datos', to='flujofirma.firmante'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.FileField(null=True, upload_to='dynamic_path'),
        ),
    ]
