# Generated by Django 5.0.6 on 2024-12-23 00:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0006_rename_usuariosistema_imagen_usuariofirmante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=255, null=True, upload_to='dynamic_path')),
                ('url_firmada_expiracion', models.DateTimeField(blank=True, null=True)),
                ('token_archivo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('secret', models.TextField()),
                ('nameArchivos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('idRequest', models.CharField(max_length=8, null=True)),
                ('nameCarpeta', models.CharField(max_length=25, null=True)),
                ('cantidadDocumentos', models.CharField(max_length=25, null=True)),
                ('url_archivos', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None)),
                ('tokenEnvio', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
