# Generated by Django 5.0.6 on 2024-12-23 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0007_archivospdf_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.TextField()),
                ('url_documento', models.TextField()),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_doc', to='flujofirma.envio')),
            ],
        ),
        migrations.CreateModel(
            name='detalleFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(max_length=50)),
                ('p_x1', models.CharField(max_length=50)),
                ('p_x2', models.CharField(max_length=50)),
                ('p_y1', models.CharField(max_length=50)),
                ('p_y2', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_detalle', to='flujofirma.envio')),
                ('firmante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmante_detalle', to='flujofirma.firmante')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_detalle', to='flujofirma.uploaddocument')),
            ],
        ),
    ]
