# Generated by Django 5.0.6 on 2024-12-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0008_uploaddocument_detallefirma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddocument',
            name='envio',
            field=models.CharField(max_length=100),
        ),
    ]
