# Generated by Django 5.0.6 on 2024-12-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0009_alter_uploaddocument_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefirma',
            name='status',
            field=models.CharField(default='NoFirmado', max_length=50),
        ),
    ]
