# Generated by Django 5.0.6 on 2024-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0010_alter_detallefirma_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmante',
            name='is_firmado',
            field=models.BooleanField(default=False),
        ),
    ]
