# Generated by Django 5.0.6 on 2024-12-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0011_firmante_is_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='document_front',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagen',
            name='document_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagen',
            name='document_rear',
            field=models.BooleanField(default=False),
        ),
    ]
