# Generated by Django 5.0.6 on 2024-12-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0012_imagen_document_front_imagen_document_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='document_front',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='document_owner',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='document_rear',
        ),
    ]
