# Generated by Django 5.0.6 on 2024-12-25 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0013_remove_imagen_document_front_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_oneshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('Firmante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmante_log', to='flujofirma.firmante')),
            ],
        ),
    ]
