# Generated by Django 5.0.6 on 2024-12-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0014_log_oneshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_oneshot',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='log_oneshot',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
