# Generated by Django 5.0.6 on 2024-12-26 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0016_firmante_is_enviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenFirmante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=50)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_orden', to='flujofirma.envio')),
                ('firmante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmante_orden', to='flujofirma.firmante')),
            ],
        ),
    ]
