# Generated by Django 5.0.6 on 2024-12-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0017_ordenfirmante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdenFirmante',
        ),
    ]
