# Generated by Django 5.0.6 on 2024-12-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0018_delete_ordenfirmante'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmante',
            name='orden_flujo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
