# Generated by Django 5.0.6 on 2024-12-29 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0019_firmante_orden_flujo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitacoraFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TokenEnvio', models.TextField()),
                ('NombreArchivo', models.TextField()),
                ('TokenArchivo', models.TextField()),
                ('EstadoFirma', models.TextField(null=True)),
                ('IDArchivoAPI', models.TextField(null=True)),
                ('FechaFirmado', models.DateField(auto_now_add=True, null=True)),
                ('url_archivo', models.TextField(null=True)),
                ('UsuarioFirmante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flujofirma.firmante')),
            ],
        ),
    ]
