# Generated by Django 5.0.6 on 2025-01-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0021_videoidentificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefirma',
            name='request_upload_document',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploaddocument',
            name='is_firmanto',
            field=models.BooleanField(default=False),
        ),
    ]
