# Generated by Django 5.0.6 on 2025-01-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0022_detallefirma_request_upload_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefirma',
            name='request_upload_document',
            field=models.TextField(null=True),
        ),
    ]
