# Generated by Django 5.0.6 on 2025-01-13 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0023_alter_detallefirma_request_upload_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitacorafirmado',
            name='documento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documento_id', to='flujofirma.uploaddocument'),
        ),
    ]
