# Generated by Django 5.0.6 on 2025-01-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujofirma', '0024_vitacorafirmado_documento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmante',
            name='fecha_enviado',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='firmante',
            name='fecha_firmado',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
