# Generated by Django 5.0.6 on 2024-12-12 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_create_signbol_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('NIT', models.CharField(max_length=50, null=True)),
                ('Sector', models.CharField(max_length=50, null=True)),
                ('NombreContacto', models.CharField(max_length=50, null=True)),
                ('NumeroContacto', models.CharField(max_length=50, null=True)),
                ('EmailContacto', models.CharField(max_length=50, null=True)),
                ('FechaRegistro', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50, null=True)),
                ('Apellidos', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('Celular', models.CharField(max_length=50, null=True)),
                ('NIT', models.CharField(max_length=50, null=True)),
                ('CUI', models.CharField(max_length=50, null=True)),
                ('FechaRegistro', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenciasSistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('FIRMAAGIL', 'FirmaAgil'), ('FLUJOFIRMASIGNBOX', 'FlujoFirmaSignbox'), ('FLUJOFIRMAONESHOT', 'FlujoFirmaOneshot')], max_length=50)),
                ('costo_tipo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_creditos', models.IntegerField()),
                ('costo_creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='app.empresasistema')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias', to='app.usuariosistema')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app.empresasistema')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RenovacionLicencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_renovacion', models.DateField(auto_now_add=True)),
                ('nueva_fecha_fin', models.DateField()),
                ('costo_renovacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_creditos', models.IntegerField()),
                ('costo_creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='app.licenciassistema')),
            ],
        ),
    ]
