# Generated by Django 5.0.6 on 2024-12-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosistema',
            name='NIT',
        ),
        migrations.AddField(
            model_name='usuariosistema',
            name='Token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
