# Generated by Django 5.0.6 on 2024-12-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_usuariosistema_nit_usuariosistema_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosistema',
            name='Token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
