# Generated by Django 5.0.6 on 2024-12-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_usuariosistema_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilsistema',
            name='Token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
