# Generated by Django 5.0.6 on 2024-12-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_empresasistema_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasistema',
            name='Token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
