# Generated by Django 5.0.6 on 2024-12-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_empresasistema_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciassistema',
            name='contrasena_billing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='licenciassistema',
            name='modalidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='licenciassistema',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='licenciassistema',
            name='usuario_billing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='licenciassistema',
            name='tipo',
            field=models.CharField(choices=[('FIRMAAGIL', 'FirmaAgil'), ('FLUJOFIRMASIGNBOX', 'FlujoFirmaSignbox'), ('FLUJOFIRMAONESHOT', 'FlujoFirmaOneshot'), ('GENERADOCS', 'GeneraDocs')], max_length=50),
        ),
    ]
