# Generated by Django 5.0.6 on 2024-12-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_licenciassistema_contrasena_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciassistema',
            name='activa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
