# Generated by Django 5.0.6 on 2024-12-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_licenciassistema_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciassistema',
            name='tipo',
            field=models.CharField(choices=[('FIRMAAGIL', 'Firma Agil'), ('FLUJOFIRMASIGNBOX', 'FF_Signbox'), ('FLUJOFIRMAONESHOT', 'FF_Oneshot'), ('GENERADOCS', 'GeneraDocs')], max_length=50),
        ),
    ]
