# Generated by Django 5.0.6 on 2024-12-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_usuariosistema_usuariogeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciassistema',
            name='tipo',
            field=models.CharField(choices=[('Firma Agil', 'Firma Agil'), ('FF_Signbox', 'FF_Signbox'), ('FF_Oneshot', 'FF_Oneshot'), ('GeneraDocs', 'GeneraDocs')], max_length=50),
        ),
    ]
