# Generated by Django 5.0.6 on 2024-12-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_licenciassistema_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciassistema',
            name='TokenAuth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
