# Generated by Django 5.0.6 on 2024-12-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_licenciassistema_tokenauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciassistema',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
