# Generated by Django 5.0.6 on 2024-12-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_licenciassistema_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renovacionlicencia',
            name='costo_creditos',
        ),
        migrations.RemoveField(
            model_name='renovacionlicencia',
            name='costo_renovacion',
        ),
        migrations.AddField(
            model_name='renovacionlicencia',
            name='Token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='renovacionlicencia',
            name='costo_renovacion_creditos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='renovacionlicencia',
            name='costo_renovacion_licencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='renovacionlicencia',
            name='fecha_anterior_emision',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='renovacionlicencia',
            name='fecha_anterior_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='renovacionlicencia',
            name='nueva_fecha_emisión',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='renovacionlicencia',
            name='nueva_fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
