# Generated by Django 5.0.6 on 2025-01-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_renovacionlicencia_costo_creditos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciassistema',
            name='consumo',
            field=models.IntegerField(null=True),
        ),
    ]
