# Generated by Django 5.0.6 on 2025-01-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_licenciassistema_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciassistema',
            name='porcentaje',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
