# Generated by Django 5.0.6 on 2025-01-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_licenciassistema_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciassistema',
            name='consumo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
