# Generated by Django 5.0.6 on 2025-01-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_costo_renovacion_creditos_renovacionlicencia_costo_creditos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciassistema',
            name='env',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
