# Generated by Django 5.0.6 on 2025-01-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_compraextraordinaria_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciassistema',
            name='acumulado_creditos',
            field=models.IntegerField(null=True),
        ),
    ]
