# Generated by Django 5.0.6 on 2025-01-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_licenciassistema_acumulado_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='token_oneshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
