# Generated by Django 5.0.6 on 2024-10-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSignAnyWhere', '0005_firmante_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmante',
            name='envelope',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
