# Generated by Django 5.0.6 on 2024-10-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaContactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('tokenAuth', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='lista_contactos',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Apellidos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Celular',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Departamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Nombres',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Periodo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Puesto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Salario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tokenAuth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='lista_contactos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ListaContactos', to='pagoplanilla.listacontactos'),
        ),
    ]
