# Generated by Django 5.0.6 on 2024-10-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0003_plantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
