# Generated by Django 5.0.6 on 2024-10-18 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0004_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='lista_contactos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='pagoplanilla.listacontactos'),
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TokenAuth', models.CharField(max_length=50, null=True)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='pagoplanilla.empresa')),
                ('ListaContactos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='pagoplanilla.listacontactos')),
                ('Plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='pagoplanilla.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='pagoplanilla.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
