# Generated by Django 5.0.6 on 2024-10-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0005_alter_contacto_lista_contactos_envios_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='Empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactoEmpresa', to='pagoplanilla.empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Ciudad',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='NIT',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Sector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='TokenAuth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='Empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresaPlantilla', to='pagoplanilla.empresa'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='Empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='pagoplanilla.empresa'),
        ),
    ]
