# Generated by Django 5.0.6 on 2024-10-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0006_contacto_empresa_empresa_ciudad_empresa_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacontactos',
            name='Empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listacontactoEmpresa', to='pagoplanilla.empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
