# Generated by Django 5.0.6 on 2024-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0007_listacontactos_empresa_alter_empresa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tokenAuth',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
