# Generated by Django 5.0.6 on 2024-10-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0008_perfilusuario_tokenauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tokenAuth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
