# Generated by Django 5.0.6 on 2024-10-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0009_alter_perfilusuario_tokenauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='NombreEnvio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='envios',
            name='UsuarioRemitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEnvio', to='pagoplanilla.perfilusuario'),
        ),
    ]
