# Generated by Django 5.0.6 on 2024-10-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0010_envios_nombreenvio_envios_usuarioremitente'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitacoraEnvios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('fechaEnvio', models.DateTimeField(auto_now_add=True)),
                ('fechaFirma', models.DateTimeField(null=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('scratchcard', models.CharField(max_length=25, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresaRemitente', to='pagoplanilla.empresa')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioRemitente', to='pagoplanilla.perfilusuario')),
            ],
        ),
    ]
