# Generated by Django 5.0.6 on 2024-10-24 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0011_vitacoraenvios'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitacoraenvios',
            name='envioVitacora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envioVitacora', to='pagoplanilla.envios'),
        ),
    ]
