# Generated by Django 5.0.6 on 2024-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0012_vitacoraenvios_enviovitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitacoraenvios',
            name='status',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
