# Generated by Django 5.0.6 on 2024-10-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0013_vitacoraenvios_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitacoraenvios',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
