# Generated by Django 5.0.6 on 2024-10-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0014_alter_vitacoraenvios_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='fechaEnvio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
