# Generated by Django 5.0.6 on 2024-10-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0015_envios_fechaenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='TotalEnvios',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
