# Generated by Django 5.0.6 on 2024-10-24 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0016_envios_totalenvios'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitacoraenvios',
            name='idUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envioUsuario', to='pagoplanilla.contacto'),
        ),
        migrations.AddField(
            model_name='vitacoraenvios',
            name='tokenAuthLista',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
