# Generated by Django 5.0.6 on 2024-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0017_vitacoraenvios_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitacoraenvios',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
