# Generated by Django 5.0.6 on 2024-11-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0018_alter_vitacoraenvios_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacontactos',
            name='CantidadContactos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listacontactos',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
