# Generated by Django 5.0.6 on 2024-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0019_listacontactos_cantidadcontactos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='FechaRegistro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='envios',
            name='fechaEnvio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='listacontactos',
            name='FechaCreacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitacoraenvios',
            name='fechaEnvio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vitacoraenvios',
            name='fechaFirma',
            field=models.DateField(null=True),
        ),
    ]
