# Generated by Django 5.0.6 on 2024-11-26 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoplanilla', '0020_alter_empresa_fecharegistro_alter_envios_fechaenvio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='pagoplanilla.empresa'),
        ),
    ]
